
from __future__ import annotations

import hashlib
import os
import pickle
import struct
from dataclasses import dataclass


# ============================================================
# Index file format
#
# Header:
#   magic       8 bytes
#   version     uint32
#   payload_len uint64
#   sha256      32 bytes
#
# Payload:
#   pickle protocol 5
#
# Note:
# This file is only used to save/load trusted indexes
# generated by this project.
# Do not load pickle index files from untrusted sources.
# ============================================================

INDEX_MAGIC = b"MMRIDX01"
INDEX_VERSION = 1

_HEADER = struct.Struct(">8sIQ32s")


@dataclass(slots=True)
class PersistedIndex:
    road: object
    store: object
    mmr_index: object
    skeleton: object
    l1_index: object
    l0_index: object

    theta: int

    trajectory_files: tuple[str, ...]


def save_index(
    index: PersistedIndex,
    file_path: str,
) -> int:
    """
    Save the complete server query index.

    Return the final file size in bytes.

    Index saving time is not included in Index Construction Time.
    """

    abs_path = os.path.abspath(
        file_path
    )

    parent = os.path.dirname(
        abs_path
    )

    if parent:
        os.makedirs(
            parent,
            exist_ok=True,
        )

    payload = pickle.dumps(
        index,
        protocol=5,
    )

    digest = hashlib.sha256(
        payload
    ).digest()

    temp_path = (
        abs_path
        + ".tmp"
    )

    with open(
        temp_path,
        "wb",
    ) as f:

        f.write(
            _HEADER.pack(
                INDEX_MAGIC,
                INDEX_VERSION,
                len(payload),
                digest,
            )
        )

        f.write(
            payload
        )

        f.flush()
        os.fsync(
            f.fileno()
        )

    os.replace(
        temp_path,
        abs_path,
    )

    return os.path.getsize(
        abs_path
    )


def load_index(
    file_path: str,
) -> PersistedIndex:
    """
    Load the complete server index.

    Index loading time is not included in Query Time.
    """

    with open(
        file_path,
        "rb",
    ) as f:

        header = f.read(
            _HEADER.size
        )

        if len(header) != _HEADER.size:
            raise ValueError(
                "Incomplete index file header"
            )

        (
            magic,
            version,
            payload_len,
            expected_digest,
        ) = _HEADER.unpack(
            header
        )

        if magic != INDEX_MAGIC:
            raise ValueError(
                "Invalid MMR index file"
            )

        if version != INDEX_VERSION:
            raise ValueError(
                f"Unsupported index version: {version}"
            )

        payload = f.read(
            payload_len
        )

        if len(payload) != payload_len:
            raise ValueError(
                "Index file ended prematurely"
            )

        if f.read(1):
            raise ValueError(
                "Extra data found at the end of the index file"
            )

    actual_digest = hashlib.sha256(
        payload
    ).digest()

    if actual_digest != expected_digest:
        raise ValueError(
            "Index file SHA-256 verification failed; "
            "the file may be corrupted or modified"
        )

    index = pickle.loads(
        payload
    )

    if not isinstance(
        index,
        PersistedIndex,
    ):
        raise ValueError(
            "Invalid index payload type"
        )

    # --------------------------------------------------------
    # Basic consistency checks
    # --------------------------------------------------------

    if index.skeleton.root_index < 0:
        raise ValueError(
            "Invalid Spatial Skeleton root"
        )

    trusted_root = (
        index.l0_index.root_hash
    )

    if (
        not isinstance(
            trusted_root,
            bytes,
        )
        or
        len(
            trusted_root
        )
        != 32
    ):
        raise ValueError(
            "Invalid index root_S"
        )

    return index
